#pragma once
#include <fstream>
#include <string>
#include <Eigen/Dense>
class vtk_write
{
public:
    std::filesystem::path filename;
    Eigen::Vector3d ox;
    Eigen::Vector3d dx;
    Eigen::Vector3i nx;
    void write_legacy_vtk2d(std::function<double(int, int)> data)
    {
        std::filesystem::create_directories(filename.parent_path());
        std::ofstream ofs(filename);
        ofs << "# vtk DataFile Version 3.0\n";
        ofs << "Legacy VTK file generated by write_legacy_vtk2d\n";
        ofs << "ASCII\n";
        ofs << "DATASET STRUCTURED_POINTS\n";
        ofs << "DIMENSIONS " << nx[0] << " " << nx[1] << " 1\n";
        ofs << "ORIGIN " << ox[0] << " " << ox[1] << " 0.0\n";
        ofs << "SPACING " << dx[0] << " " << dx[1] << " 1.0\n";
        ofs << "POINT_DATA " << nx[0] * nx[1] << "\n";
        ofs << "SCALARS scalars double\n";
        ofs << "LOOKUP_TABLE default\n";
        for (int j = 0; j < nx[1]; ++j)
            for (int i = 0; i < nx[0]; ++i)
                ofs << data(i,j) << "\n";
        ofs.close();
    }
};
