// vtk_myIO.hpp    僕のVTKの入出力
#pragma once
#include <fstream>
#include <string>
#include <Eigen/Dense>
#include <vtkSmartPointer.h>
#include <vtkImageData.h>
#include <vtkDoubleArray.h>
#include <vtkPointData.h>
#include <vtkXMLImageDataWriter.h>

class vtk_myIO
{
public:
    std::filesystem::path filename;
    Eigen::Vector3d ox;
    Eigen::Vector3d dx;
    Eigen::Vector3i nx;
    void write_xml_vti2d(std::function<double(int, int)> data)
    {
        // VTKのImageDataオブジェクト作成
        auto image = vtkSmartPointer<vtkImageData>::New();
        image->SetDimensions(nx[0], nx[1], nx[2]);
        image->SetOrigin(ox[0], ox[1], ox[2]);
        image->SetSpacing(dx[0], dx[1], dx[2]);
        // スカラー値の配列を作成
        auto ARR= vtkSmartPointer<vtkDoubleArray>::New();
        ARR->SetName("pressure");
        ARR->SetNumberOfComponents(1);
        ARR->SetNumberOfTuples(nx[0] * nx[1]);
        image->GetPointData()->AddArray(ARR);
        for (int j = 0; j < nx[1]; ++j)
            for (int i = 0; i < nx[0]; ++i)
                ARR->SetValue(j * nx[0] + i, data(i, j));
        // スカラー値の配列をアクティブにする
        image->GetPointData()->SetActiveScalars("pressure");
        // XML VTKファイル（.vti）で出力
        auto writer = vtkSmartPointer<vtkXMLImageDataWriter>::New();
        std::filesystem::create_directories(filename.parent_path());
        writer->SetFileName(filename.c_str());
        writer->SetInputData(image);
        writer->SetCompressorTypeToLZMA(); // LZMA圧縮（zlibより高圧縮）
        writer->Write();
        std::cout << "VTK file written: " << filename.string() << std::endl;
    }
    void write_legacy_vti2d(std::function<double(int, int)> data)
    {
        std::filesystem::create_directories(filename.parent_path());
        std::ofstream ofs(filename);
        ofs << "# vtk DataFile Version 3.0\n";
        ofs << "Legacy VTK file generated by write_legacy_vtk2d\n";
        ofs << "ASCII\n";
        ofs << "DATASET STRUCTURED_POINTS\n";
        ofs << "DIMENSIONS " << nx[0] << " " << nx[1] << " 1\n";
        ofs << "ORIGIN " << ox[0] << " " << ox[1] << " 0.0\n";
        ofs << "SPACING " << dx[0] << " " << dx[1] << " 1.0\n";
        ofs << "POINT_DATA " << nx[0] * nx[1] << "\n";
        ofs << "SCALARS scalars double\n";
        ofs << "LOOKUP_TABLE default\n";
        ofs << std::setprecision(15) << std::scientific;
        for (int j = 0; j < nx[1]; ++j)
            for (int i = 0; i < nx[0]; ++i)
                ofs << data(i, j) << "\n";
        ofs.close();
    }
};
